### PR TITLE
Add unit test for fetching the list of @category values

### PR DESCRIPTION
**Pull request by mudrd8mz**
It raised my attention to see that I got an error
https://integration.moodle.org/job/Precheck%20remote%20branch/92421/artifact/work/smurf.html#phpdoc

"Category admin is not valid"

even when the "admin" should be considered valid core API. I realized the reason was that the heading in the docs was

```
=== Admin settings (admin) ===
```

and because there was no "API" mentioned in it, the "admin" was not parsed as a valid category value.

I was able to fix this easily by changing the section title in the docs (and one another, too) -  https://docs.moodle.org/dev/index.php?title=Core_APIs&type=revision&diff=57824&oldid=57817

However, I thought it would be nice to have the check covered by a unit test so I added one.

Also fix the docs page URL and make the regexp search a bit more robust
just in case the HTML change a bit.

### CODE REVIEW

**Comment by stronk7** [comment]
Aha good one... i remember some issues in the tracker commenting about this and never had time to look, will search for them now.

Only little detail I'd suggest is to provide an actual [rules/coreapis.txt](https://github.com/moodlehq/moodle-local_moodlecheck/blob/master/rules/coreapis.txt) file, including the latest changes you've performed there. It's used when connectivity to docs fail, so better having it updated.

Ciao :-)

**Comment by mudrd8mz** [comment]
Ah good catch! I had forgotten about that one.

* Updated the coreapis.txt file with the latest content.
* Updated the function so that we can now explicitly test the offline mode (and thence the contents of the shipped file) too.

**Comment by stronk7** [comment]
I've just merged master to fix the conflict introduced by merging #60 . Will proceed with this once travis tells us that the conflict resolution (I did it straight in GH's UI) was ok.

**Comment by stronk7** [comment]
And CiBoT is already using it.

moodle-plugin-ci will soon... we are deciding about to start tagging this (moodlecheck) for automatic updates elsewhere.

**Pull request merged**
